fix husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -8,11 +8,11 @@
 . "$(dirname "$0")/_/husky.sh"
 
 # bash echo color
-RED='\033[1;31m'
-GREEN='\033[1;32m'
-BLUE='\033[1;36m'
-BOLD='\033[1;37m'
-NC='\033[0m'
+RED='\033[1;31m' # 赤色のテキストを表すエスケープシーケンス
+GREEN='\033[1;32m' # 緑色のテキストを表すエスケープシーケンス
+BLUE='\033[1;36m' # 青色のテキストを表すエスケープシーケンス
+BOLD='\033[1;37m' # 太字のテキストを表すエスケープシーケンス
+NC='\033[0m' # テキストの色をリセットするエスケープシーケンス
 
 echo "\n 🚧🏗️  ${BOLD}Checking format, lint and types in your project before committing${NC}"
 
@@ -31,21 +31,20 @@ npm run lint:js ||
 )
 
 # Check tsconfig standards
-npm run types ||
+npm run compile ||
 (
     echo "\n ❌🟦 Type check ${RED}Failed${NC}. 🟦❌\n Make the changes required above.\n"
     false;
 )
 
 # If everything passes... Now we can build
-# echo "🔥🚀 ${BOLD}All passed... Now we can build.${NC} 🚀🔥"
-echo "🔥🚀 ${BOLD}All passed...${NC} 🚀🔥"
+echo "🔥🚀 ${BOLD}All passed... Now we can build.${NC} 🚀🔥"
 
-# npm run build ||
-# (
-#     echo "\n ❌🟩 Next build ${RED}Failed${NC}. 🟩❌\n View the errors above to see why.\n"
-#     false;
-# )
+npm run build ||
+(
+    echo "\n ❌🟩 Next build ${RED}Failed${NC}. 🟩❌\n View the errors above to see why.\n"
+    false;
+)
 
 # If everything passes... Now we can commit
-# echo "✅✅ ${GREEN}Build is completed... I am committing this now.${NC} ✅✅\n"
+echo "✅✅ ${GREEN}Build is completed... I am committing this now.${NC} ✅✅\n"
